import{a as h,i as c,S as f}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const s of a.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const p=r=>`
    <li class='gallery-card'>
    <a class='gallery-link' href='${r.largeImageURL}'>
    <img class='galley-img' src='${r.webformatURL}' alt='${r.tags}' width='360'  '/>
    </a>
    <div class='description'>
    <p>Likes: ${r.likes}</p>
    <p>Views: ${r.views}</p> 
    <p>Comments: ${r.comments}</p>
    <p> Downloads: ${r.downloads}</p>
    </div>
    </li>
    `,m=(r,t)=>{const o={params:{key:"48282241-c94e9d668c7a92092d53abf55",q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"}};return h.get("https://pixabay.com/api/",o)},g=document.querySelector(".search-form"),d=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");let i=1,y="";l.style.display="none";const L=async r=>{d.innerHTML="",l.style.display="inline-block";try{if(r.preventDefault(),y=r.currentTarget.elements.search_input.value.trim(),y===""){c.warning({title:"Caution",message:"You forgot to full fill searching area"});return}i=1,u.classList.add("is-hidden");const{data:t}=await m(y,i);if(t.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),d.innerHTML="",g.reset();return}t.total>10&&(u.classList.remove("is-hidden"),u.addEventListener("click",S));const o=t.hits.map(e=>p(e)).join("");d.innerHTML=o,new f(".gallery a",{captionsData:"alt",captions:!0,captionDelay:250}).refresh()}catch(t){t.message==="404"&&c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),console.log(t)}finally{l.style.display="none"}};g.addEventListener("submit",L);const S=async r=>{i+=1,l.style.display="inline-block";try{const{data:t}=await m(y,i);console.dir({data:t});const o=t.hits.map(s=>p(s)).join("");d.insertAdjacentHTML("beforeend",o);const e=document.querySelector(".gallery-card").getBoundingClientRect();window.scrollBy({top:2*e.height,behavior:"smooth"});const a=Math.ceil(t.totalHits/15);i===a&&(u.classList.add("is-hidden"),c.info({message:"We are sorry, but you have reached the end of search results."}))}catch(t){console.log(t)}finally{l.style.display="none"}};
//# sourceMappingURL=index.js.map
